apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    name: nginx-2
spec:
  containers:
  - name: nginx-2
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
